apiVersion: v1
kind: Service
metadata:
  name: socmed
spec:
  selector:
    app: socmed
  ports:
    - protocol: TCP
      port: 8000
---
apiVersion : apps/v1
kind: Deployment
metadata:
  name: socmed 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: socmed
  template:
    metadata:
      labels:
        app: socmed 
    spec:
      containers:
      - name: socmed 
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "400m"
        image: cilsyari/socmed:branch-appversion
        ports:
        - containerPort: 8000
---
