apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: jnlp
    image: gcr.io/kaniko-project/executor:latest
    imagePullPolicy: Always
    args:
    - "--dockerfile=socmed/ops/socmed.Dockerfile"
    - "--context=dir://socmed/."
    - "--destination=cilsyari/socmed:ari"
    volumeMounts:
      - name: docker-config
        mountPath: /kaniko/.docker/
  restartPolicy: Never
  volumes:
    - name: docker-config
      secret:
      secretName: regcred
      items:
       - key: .dockerconfigjson
         path: config.json